<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        /*
        1、指定回调函数的方式更加灵活：
        旧的：必须在启动异步任务前指定
        promise：启动异步任务=>返回promise对象=>给promise对象绑定回调函数(甚至可以在异步任务结束之后指定)

        2、支持链式调用，可以解决回调地狱问题
        什么是回调地狱？回调函数嵌套调用，外部回调函数异步执行的结果是嵌套的回调函数执行的条件
        回调地狱的缺点？不便于阅读/不便于异常处理
        解决方案？promise链式调用
        终极解决方案？async/await
        */
       
        //成功的回调函数
        function successCallback(result){
            console.log('成功'+result);
        }
        //失败的回调函数
        function failCallback(error){
            console.log('失败'+error);
        }
        //1.使用纯回调函数写异步任务
        createAudioFileAsync(audioSettings,successCallback,failCallback);

        //2、使用Promise
        const promise = createAudioFileAsync(audioSettings);
        setTimeout(()=>{
            promise.then(successCallback,failCallback);
        },3000);

        //回调地狱
        doSomething(function(result){
            doSomethingElse(result,function(newResult){
                doThirdThing(newResult,function(finalResult){
                    console.log('Got the final result'+finalResult);
                },failCallback)
            },failCallback)
        },failCallback);

        //2.2使用Promise的链式调用解决回调地狱
        doSomething()
        .then(function(result){
            return doSomethingElse(result);
        })
        .then(function(newResult){
            return doThirdThing(newResult);
        })
        .then(function(finalResult){
            console.log('Got the final result'+finalResult);
        })
        .catch(failCallback);//只需在最后添加错误处理即可，称之为异常穿透，所有的promise错误处理都直接到最后接收

        //3、async/await：回调地狱的终级解决方案(因为这里没有回调函数，看上去就跟同步任务一样，编译后存在回调函数)
        async function request(){
            try{
                const result = await doSomething();
                const newResult = await doSomethingElse(result);
                const finalResult = await doThirdThing(newResult);
                console.log('Got the final result'+finalResult);
            }catch(error){
                failCallback(error); 
            }
        }
    </script>
</body>
</html>